name: Test Build Github Packages

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@97c170d70b5f8bfc77e6b23e68381f217cb64ded
        with:
          images: ghcr.io/${{ github.actor }}/${{ secrets.image }}
      - run: |
          docker build . -t ghcr.io/${{ github.actor}}/${{ secrets.image }}:test
