name: Release Github Packages

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.GH_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@97c170d70b5f8bfc77e6b23e68381f217cb64ded
        with:
          images: ghcr.io/${{ secrets.USER }}/${{ secrets.IMAGE }}
      - run: |
          docker build . -t ghcr.io/${{ secrets.USER }}/${{ secrets.IMAGE }}:test
